import Link from 'next/link';

export default function Home() {
  return (
    <main className='w-full'>
      <h1>Forza App</h1>
      <p>Generated by Mariusz Krawczyk</p>
      <Link href='/login'>Login</Link>
    </main>
  );
}
