import Link from 'next/link';

export default function Home() {
  return (
    <main className='w-full flex justify-center items-center flex-col'>
      <h1 className='text-7xl text-red-600 font-bold p-3'>Forza App</h1>
      <p>Generated by Mariusz Krawczyk</p>
      <p>
        <Link href='/login'>Login</Link>
      </p>
    </main>
  );
}
